### ISSUE TITLE
Sample code is is flawed?   Untested?

### ISSUE THREAD

**Issue by SolidStateLEDLighting** [aurelia/documentation#347] opened 2017-06-15 20:06 UTC
http://aurelia.io/hub.html#/doc/article/aurelia/dialog/latest/dialog-basics/5

Please examine the sample code on your page:

export class Prompt {
  static inject = [DialogController];

  constructor(controller){
    this.controller = controller;
    this.answer = null;

    controller.settings.lock = false;
    controller.settings.centerHorizontalOnly = true;
  }
}

1) You omitted the DialogController import statement.
2) What is the member "answer" doing here?   Is this a flaw or am I missing the understanding on what it is used for?
3) Again, code on entire page will not translate to TS examples.

**Comment by EisenbergEffect** [comment] 2017-06-16 03:13
@PWKad Can you look at this?

**Comment by PWKad** [comment] 2017-06-19 14:57
The code is fine and has been tested.  Please refer to the documentation if there are questions regarding return values and usage and such.

We can add an import statement no big deal.  TypeScript translations welcome.  Tracking at https://github.com/aurelia/dialog/issues/305 , please close this issue.

**Comment by avrahamcool** [comment] 2019-01-30 23:20
I think this can be closed.
the link in the issue is no longer active - because this section was re-written.

**Closed** 2019-01-30 23:34 UTC
Labels: bug, documentation
